@startuml
left to right direction
actor Comprador
rectangle Rifa {
    (Buscar ingressos disponíveis)
    (Selecionar ingressos)
    (Realizar pagamento)    
}
:Comprador: --> (Buscar ingressos disponíveis)
:Comprador: --> (Selecionar ingressos)
:Comprador: --> (Realizar pagamento)
@enduml