@startuml
title Modelo de Dados do Sistema

package "shared" {
    entity User {
        +id: Long
        -nome: String
        -email: String
        -user_type: String
        -foto_de_perfil: String
    }
    entity BibliotecaAdmin {
        +id: Long
        -userId: Long
        -cpf: String
    }
    entity Admin {
        +id: Long
        -userId: Long
        -cpf: String
    }
    entity LoggableUser {
        -senha: String
    }
    entity Doador {
        +id: Long
        -userId: Long
        -telefone: String
        -endereco: String
    }
    entity RifaComprador {
        +id: Long
        -userId: Long
        -cep: String
        -complemento: String
        -permiteEnviarPropagandas: Boolean
    }
    entity RifaAdmin {
        +id: Long
        -userId: Long
        -cpf: String
    }
    entity DoadorJuridico {
        +id: Long
        -doadorId: Long
        -cnpj: String
        -razaoSocial: String
    }
    
    entity DoadorPessoaFisica {
        +id: Long
        -doadorId: Long
        -cpf: String
        -cep: String
    }
    entity BibliotecaLeitor {
        +id: Long
        -userId: Long
        -matricula: String
        -dataDeNascimento: LocalDate
        -complemento: String
        -endereco: String
    }
}

package "rifa" {
    entity Rifa {
        +id: Long
        -titulo: String
        -descricao: String
        -dataSorteio: Date
        -qtdBilhetesTotal: Long
        -qtdBilhetesDisponiveis: Long
        -totalValorArrecadado: BigDecimal
        -statusRifa: String
        -corInicioFundo: String
        -corMeioFundo: String
        -corFimFundo: String
        -fotos: String 
    }
    entity RifaFoto {
        +id: Long
        -url: String
        -rifaId: Long
    }

    entity Bilhete {
        +id: Long
        -numeroBilhete: String
        -status: String
        ' --- Chaves Estrangeiras ---
        -rifaId: Long
        -userId: Long
    }
}

package "Doação" {
    entity Doacao {
        +id: Long
        -valor: BigDecimal
        -dataDoacao: Date
        -descricao: String
        -avaliacaoDoacao: String
        -descricacaoDoacao: String
        ' --- Chave Estrangeira ---
        -userId: Long
    }
    entity DoacaoFoto {
        +id: Long
        -url: String
        -doacaoId: Long
    }
    entity DoacaoItem {
        +id: Long
        -statusItem: String
        -doacaoId: Long
    }
    entity DoacaoValor {
        +id: Long
        -metodoPagamento: String
        -doacaoId: Long
    }
    entity DoacaoEvento {
        +id: Long
        -numeroDePessoas: Integer
        -doacaoId: Long
    }   
}

package "Biblioteca" {
    entity PalavraChave {
        +id: Long
        -palavra-chave: String
    }
    entity Livro {
        +id: Long
        -titulo: String
        -subtitulo: String
        -resumo: String
        -paginas: Integer
        -classificacao: String
        -autorPrincipal: String
        -autorSecundario: String
        -observacao: String
        -cutter: String
        -dataDeRegistro: Date
        -isbn: String
        -editora: String
        -edicao: String
        -ano: String
        -anoPublicacao: Date
        -palavraChaveId: Long
    }

    entity Exemplar {
        +id: Long
        -codigo: String
        -numeroExemplar: String
        -numeroDePatrimonio: String
        -volume: Integer
        -statusExemplar: String
        -estadoDeConservacao: String
        -dataDeRegistro: Date
        ' --- Chave Estrangeira ---
        -livroId: Long
    }
    entity Emprestimo {
        +id: Long
        -data: Instant
        -prazoDeDevolucao: LocalDate
        -statusEmprestimo: String
        ' --- Chaves Estrangeiras ---
        -leitorId: Long
        -exemplarId: Long
    }
    entity ExemplarHistory {
        +id: Long
        -createdAt: Instant
        -observacao: String
        -exemplarId: Long
        -action: String
    }
    entity EmprestimoHistory {
        +id: Long
        -createdAt: Instant
        -observacao: String
        -emprestimoId: Long
        -action: String
    }
}

' --- Relacionamentos ---
Rifa "1" -- "0..*" Bilhete : possui
User "1" -- "0..*" Bilhete : compra
User "1" -- "0..*" Doacao : registra
User "1" -- "0..*" Emprestimo : (Leitor) realiza
Livro "1" -- "1..*" Exemplar : possui
Exemplar "1" -- "0..*" Emprestimo : é emprestado
Exemplar "1" -- "0..*" ExemplarHistory : tem histórico
User "1" -- "0..1" Doador : é
LoggableUser <|-- BibliotecaAdmin
LoggableUser <|-- Admin
LoggableUser <|-- RifaAdmin
Doador <|-- DoadorJuridico
Doador <|-- DoadorPessoaFisica
User <|-- LoggableUser
User "1" -- "0..1" RifaComprador : é
User "1" -- "0..1" BibliotecaLeitor : é
Exemplar "1" -- "0..*" EmprestimoHistory : tem histórico
ExemplarHistory o-- Exemplar : referência
EmprestimoHistory o-- Emprestimo : referência
PalavraChave "0..*" -- "0..*" Livro : associa
RifaFoto "0..*" -- "1" Rifa : pertence
DoacaoFoto "0..*" -- "1" Doacao : pertence
Doacao <|-- DoacaoItem
Doacao <|-- DoacaoValor
Doacao <|-- DoacaoEvento

@enduml